class_name WeaponStats
extends RefCounted

## Tabela de stats das armas de crate (escopetas, automaticas, rifles e armas
## futuristas). Fonte unica: crates, drops, municao de classe, modelo na mao e
## tracer leem daqui. A faca e a
## pistola padrao nao tem durabilidade e sao permanentes; as de crate se
## desgastam a cada disparo e quebram em 0 (fallback para a faca).
## Uso:
##   var stats := WeaponStats.stats_for(PlayerCharacter.Weapon.SHOTGUN)
##   if stats.is_empty(): return # arma padrao

## Durabilidade triplicada (pedido de jogo): armas de crate quebravam rapido demais.
## Mesma ordem de PlayerCharacter.Weapon (o jogador usa os mesmos inteiros).
enum Kind { KNIFE, PISTOL, SHOTGUN, UZI, MAGNUM, DOUBLE_BARREL, CARBINE, SAWED_OFF, AUTO_SHOTGUN, LASER_RIFLE, PLASMA_SMG, RAILGUN, AK47, M4, AUG, BERETTA, SNIPER, BAZOOKA, CROSSBOW, GRENADE_LAUNCHER }

const DEFAULT_TRACER_COLOR := Color(1.0, 0.72, 0.08)

const STATS_BY_KIND: Dictionary = {
	Kind.SHOTGUN: {
		"label": "Escopeta",
		"damage": 10,
		"pellets": 8,
		"mag_size": 6,
		"max_reserve": 24,
		"grant_reserve": 24,
		"attack_cooldown": 0.85,
		"max_durability": 120,
		"degraded_below": 48,
		"jam_chance": 0.15,
		"spread_deg": 9.0,
		"degraded_spread_deg": 16.0,
		"noise_radius": 75.0,
		"color": Color(0.55, 0.36, 0.14),
		"model": "shotgun",
		"tracer_color": Color(1.0, 0.8, 0.35),
		"tracer_scale": Vector3(0.7, 0.7, 0.5),
		"recoil": 0.16,
		"recoil_lift": 0.12,
		"flash_scale": 1.3,
		"sound": "shotgun",
		"tracer_speed": 120.0,
	},
	Kind.UZI: {
		"label": "Uzi",
		"damage": 8,
		"pellets": 1,
		"mag_size": 30,
		"max_reserve": 240,
		"grant_reserve": 240,
		"attack_cooldown": 0.11,
		"is_auto": true,
		"max_durability": 360,
		"degraded_below": 120,
		"jam_chance": 0.06,
		"spread_deg": 3.0,
		"degraded_spread_deg": 6.0,
		"noise_radius": 65.0,
		"color": Color(0.16, 0.17, 0.2),
		"model": "smg",
		"tracer_color": Color(1.0, 0.9, 0.3),
		"tracer_scale": Vector3(0.6, 0.6, 0.7),
		"recoil": 0.04,
		"recoil_lift": 0.03,
		"flash_scale": 0.7,
		"sound": "smg",
		"tracer_speed": 140.0,
	},
	Kind.MAGNUM: {
		"label": "Magnum",
		"damage": 55,
		"pellets": 1,
		"mag_size": 6,
		"max_reserve": 18,
		"grant_reserve": 18,
		"attack_cooldown": 0.65,
		"max_durability": 90,
		"degraded_below": 36,
		"jam_chance": 0.10,
		"spread_deg": 1.0,
		"degraded_spread_deg": 2.5,
		"noise_radius": 70.0,
		"color": Color(0.3, 0.1, 0.12),
		"model": "revolver",
		"tracer_color": Color(1.0, 0.55, 0.15),
		"tracer_scale": Vector3(1.3, 1.3, 1.2),
		"recoil": 0.2,
		"recoil_lift": 0.25,
		"flash_scale": 1.5,
		"sound": "magnum",
		"tracer_speed": 130.0,
	},
	Kind.DOUBLE_BARREL: {
		"label": "Escopeta Dupla",
		"damage": 12,
		"pellets": 12,
		"mag_size": 2,
		"max_reserve": 14,
		"grant_reserve": 14,
		"attack_cooldown": 0.7,
		"max_durability": 78,
		"degraded_below": 30,
		"jam_chance": 0.12,
		"spread_deg": 14.0,
		"degraded_spread_deg": 20.0,
		"noise_radius": 80.0,
		"color": Color(0.42, 0.2, 0.1),
		"model": "double_barrel",
		"tracer_color": Color(1.0, 0.65, 0.25),
		"tracer_scale": Vector3(0.7, 0.7, 0.5),
		"recoil": 0.24,
		"recoil_lift": 0.18,
		"flash_scale": 1.8,
		"sound": "shotgun",
		"tracer_speed": 120.0,
	},
	Kind.CARBINE: {
		"label": "Carabina",
		"damage": 48,
		"pellets": 1,
		"mag_size": 10,
		"max_reserve": 60,
		"grant_reserve": 60,
		"attack_cooldown": 0.5,
		"max_durability": 240,
		"degraded_below": 84,
		"jam_chance": 0.08,
		"spread_deg": 0.7,
		"degraded_spread_deg": 2.0,
		"noise_radius": 72.0,
		"color": Color(0.14, 0.22, 0.16),
		"model": "rifle",
		"tracer_color": Color(0.95, 0.95, 0.75),
		"tracer_scale": Vector3(0.8, 0.8, 1.6),
		"recoil": 0.1,
		"recoil_lift": 0.06,
		"flash_scale": 1.0,
		"sound": "rifle",
		"tracer_speed": 150.0,
	},
	Kind.SAWED_OFF: {
		"label": "Escopeta Serrada",
		"damage": 15,
		"pellets": 10,
		"mag_size": 2,
		"max_reserve": 20,
		"grant_reserve": 20,
		"attack_cooldown": 0.45,
		"max_durability": 90,
		"degraded_below": 30,
		"jam_chance": 0.12,
		"spread_deg": 22.0,
		"degraded_spread_deg": 30.0,
		"noise_radius": 80.0,
		"color": Color(0.35, 0.2, 0.1),
		"model": "short_shotgun",
		"tracer_color": Color(1.0, 0.45, 0.2),
		"tracer_scale": Vector3(0.8, 0.8, 0.4),
		"recoil": 0.26,
		"recoil_lift": 0.22,
		"flash_scale": 2.0,
		"sound": "shotgun",
		"tracer_speed": 110.0,
	},
	Kind.AUTO_SHOTGUN: {
		"label": "Escopeta Automatica",
		"damage": 9,
		"pellets": 6,
		"mag_size": 12,
		"max_reserve": 48,
		"grant_reserve": 36,
		"attack_cooldown": 0.28,
		"is_auto": true,
		"max_durability": 150,
		"degraded_below": 50,
		"jam_chance": 0.1,
		"spread_deg": 11.0,
		"degraded_spread_deg": 18.0,
		"noise_radius": 80.0,
		"color": Color(0.2, 0.22, 0.24),
		"model": "auto_shotgun",
		"tracer_color": Color(1.0, 0.7, 0.1),
		"tracer_scale": Vector3(0.65, 0.65, 0.5),
		"recoil": 0.12,
		"recoil_lift": 0.07,
		"flash_scale": 1.2,
		"sound": "shotgun",
		"tracer_speed": 120.0,
	},
	Kind.LASER_RIFLE: {
		"label": "Rifle Laser",
		"damage": 70,
		"pellets": 1,
		"mag_size": 12,
		"max_reserve": 60,
		"grant_reserve": 48,
		"attack_cooldown": 0.4,
		"max_durability": 200,
		"degraded_below": 60,
		"jam_chance": 0.04,
		"spread_deg": 0.2,
		"degraded_spread_deg": 1.0,
		"noise_radius": 40.0,
		"color": Color(0.85, 0.88, 0.92),
		"model": "sci_rifle",
		"tracer_color": Color(0.2, 0.9, 1.0),
		"tracer_scale": Vector3(0.5, 0.5, 4.0),
		"recoil": 0.03,
		"recoil_lift": 0.02,
		"flash_scale": 1.1,
		"sound": "laser",
		"tracer_speed": 300.0,
	},
	Kind.PLASMA_SMG: {
		"label": "SMG de Plasma",
		"damage": 16,
		"pellets": 1,
		"mag_size": 40,
		"max_reserve": 240,
		"grant_reserve": 200,
		"attack_cooldown": 0.08,
		"is_auto": true,
		"max_durability": 400,
		"degraded_below": 120,
		"jam_chance": 0.03,
		"spread_deg": 4.0,
		"degraded_spread_deg": 7.0,
		"noise_radius": 45.0,
		"color": Color(0.25, 0.1, 0.35),
		"model": "sci_smg",
		"tracer_color": Color(0.9, 0.25, 1.0),
		"tracer_scale": Vector3(1.4, 1.4, 0.8),
		"recoil": 0.04,
		"recoil_lift": 0.03,
		"flash_scale": 1.0,
		"sound": "plasma",
		"tracer_speed": 160.0,
	},
	## Railgun: tiro atravessa ate `pierce` alvos na mesma linha.
	Kind.RAILGUN: {
		"label": "Railgun",
		"damage": 260,
		"pellets": 1,
		"pierce": 6,
		"mag_size": 3,
		"max_reserve": 15,
		"grant_reserve": 12,
		"attack_cooldown": 1.3,
		"max_durability": 60,
		"degraded_below": 18,
		"jam_chance": 0.05,
		"spread_deg": 0.0,
		"degraded_spread_deg": 0.8,
		"noise_radius": 90.0,
		"color": Color(0.1, 0.12, 0.16),
		"model": "railgun",
		"tracer_color": Color(0.3, 1.0, 0.5),
		"tracer_scale": Vector3(0.9, 0.9, 5.0),
		"recoil": 0.4,
		"recoil_lift": 0.1,
		"flash_scale": 2.2,
		"sound": "railgun",
		"tracer_speed": 320.0,
	},
	Kind.AK47: {
		"label": "AK-47",
		"damage": 30,
		"pellets": 1,
		"mag_size": 30,
		"max_reserve": 180,
		"grant_reserve": 120,
		"attack_cooldown": 0.12,
		"is_auto": true,
		"max_durability": 300,
		"degraded_below": 100,
		"jam_chance": 0.06,
		"spread_deg": 3.5,
		"degraded_spread_deg": 7.0,
		"noise_radius": 75.0,
		"color": Color(0.35, 0.22, 0.12),
		"model": "ak",
		"tracer_color": Color(1.0, 0.6, 0.2),
		"tracer_scale": Vector3(0.8, 0.8, 1.1),
		"recoil": 0.07,
		"recoil_lift": 0.06,
		"flash_scale": 1.0,
		"sound": "heavy_rifle",
		"tracer_speed": 150.0,
	},
	Kind.M4: {
		"label": "M4",
		"damage": 24,
		"pellets": 1,
		"mag_size": 30,
		"max_reserve": 210,
		"grant_reserve": 150,
		"attack_cooldown": 0.09,
		"is_auto": true,
		"max_durability": 330,
		"degraded_below": 110,
		"jam_chance": 0.04,
		"spread_deg": 2.2,
		"degraded_spread_deg": 5.0,
		"noise_radius": 70.0,
		"color": Color(0.12, 0.12, 0.13),
		"model": "assault_rifle",
		"tracer_color": Color(1.0, 0.95, 0.5),
		"tracer_scale": Vector3(0.7, 0.7, 1.1),
		"recoil": 0.05,
		"recoil_lift": 0.04,
		"flash_scale": 0.9,
		"sound": "rifle",
		"tracer_speed": 160.0,
	},
	Kind.AUG: {
		"label": "AUG",
		"damage": 27,
		"pellets": 1,
		"mag_size": 30,
		"max_reserve": 180,
		"grant_reserve": 120,
		"attack_cooldown": 0.1,
		"is_auto": true,
		"max_durability": 300,
		"degraded_below": 100,
		"jam_chance": 0.04,
		"spread_deg": 1.6,
		"degraded_spread_deg": 4.0,
		"noise_radius": 70.0,
		"color": Color(0.3, 0.36, 0.24),
		"model": "bullpup",
		"tracer_color": Color(0.8, 1.0, 0.5),
		"tracer_scale": Vector3(0.7, 0.7, 1.2),
		"recoil": 0.05,
		"recoil_lift": 0.035,
		"flash_scale": 0.9,
		"sound": "rifle",
		"tracer_speed": 160.0,
	},
	Kind.BERETTA: {
		"label": "Beretta",
		"damage": 28,
		"pellets": 1,
		"mag_size": 15,
		"max_reserve": 90,
		"grant_reserve": 60,
		"attack_cooldown": 0.2,
		"max_durability": 400,
		"degraded_below": 120,
		"jam_chance": 0.03,
		"spread_deg": 1.5,
		"degraded_spread_deg": 3.0,
		"noise_radius": 55.0,
		"color": Color(0.1, 0.1, 0.11),
		"model": "handgun",
		"tracer_color": Color(1.0, 1.0, 0.8),
		"tracer_scale": Vector3(0.7, 0.7, 0.8),
		"recoil": 0.06,
		"recoil_lift": 0.08,
		"flash_scale": 0.8,
		"sound": "pistol",
		"tracer_speed": 130.0,
	},
	Kind.SNIPER: {
		"label": "Sniper",
		"damage": 320,
		"pellets": 1,
		"mag_size": 5,
		"max_reserve": 25,
		"grant_reserve": 20,
		"attack_cooldown": 1.5,
		"pierce": 2,
		"max_durability": 90,
		"degraded_below": 30,
		"jam_chance": 0.05,
		"spread_deg": 0.0,
		"degraded_spread_deg": 0.5,
		"noise_radius": 95.0,
		"color": Color(0.2, 0.24, 0.18),
		"model": "sniper",
		"tracer_color": Color(0.6, 0.85, 1.0),
		"tracer_scale": Vector3(0.6, 0.6, 3.5),
		"recoil": 0.3,
		"recoil_lift": 0.2,
		"flash_scale": 1.6,
		"sound": "sniper",
		"tracer_speed": 260.0,
	},
	## Bazuca: explode no primeiro impacto ferindo tudo em `explosive_radius`.
	Kind.BAZOOKA: {
		"label": "Bazuca",
		"damage": 150,
		"pellets": 1,
		"mag_size": 1,
		"max_reserve": 6,
		"grant_reserve": 4,
		"attack_cooldown": 2.2,
		"explosive_radius": 5.0,
		"max_durability": 30,
		"degraded_below": 10,
		"jam_chance": 0.05,
		"spread_deg": 0.0,
		"degraded_spread_deg": 1.0,
		"noise_radius": 110.0,
		"color": Color(0.25, 0.32, 0.18),
		"model": "launcher",
		"tracer_color": Color(1.0, 0.4, 0.1),
		"tracer_scale": Vector3(2.4, 2.4, 1.6),
		"recoil": 0.35,
		"recoil_lift": 0.3,
		"flash_scale": 2.4,
		"sound": "launcher",
		"tracer_speed": 100.0,
	},
	## Besta: quase sem som (a horda nao ouve de longe) e a seta atravessa a fila.
	Kind.CROSSBOW: {
		"label": "Besta",
		"damage": 85,
		"pellets": 1,
		"pierce": 4,
		# Besta de repeticao: com pente 1 cada segundo clique so recarregava.
		"mag_size": 5,
		"max_reserve": 30,
		"grant_reserve": 20,
		"attack_cooldown": 0.9,
		"max_durability": 150,
		"degraded_below": 45,
		"jam_chance": 0.05,
		"spread_deg": 0.0,
		"degraded_spread_deg": 2.5,
		"noise_radius": 8.0,
		"color": Color(0.36, 0.24, 0.12),
		"model": "crossbow",
		"tracer_color": Color(0.85, 0.95, 0.75),
		"tracer_scale": Vector3(0.5, 0.5, 2.2),
		"recoil": 0.05,
		"recoil_lift": 0.04,
		"flash_scale": 0.2,
		"sound": "crossbow",
		"tracer_speed": 70.0,
	},
	## Lanca-granadas: tambor de 6, explosao menor que a bazuca e cadencia maior.
	Kind.GRENADE_LAUNCHER: {
		"label": "Lanca-granadas",
		"damage": 95,
		"pellets": 1,
		"mag_size": 6,
		"max_reserve": 24,
		"grant_reserve": 12,
		"attack_cooldown": 0.75,
		"explosive_radius": 3.8,
		"max_durability": 90,
		"degraded_below": 30,
		"jam_chance": 0.06,
		"spread_deg": 1.0,
		"degraded_spread_deg": 4.0,
		"noise_radius": 95.0,
		"color": Color(0.3, 0.36, 0.22),
		"model": "grenade_launcher",
		"tracer_color": Color(0.55, 1.0, 0.2),
		"tracer_scale": Vector3(1.6, 1.6, 1.0),
		"recoil": 0.22,
		"recoil_lift": 0.2,
		"flash_scale": 1.8,
		"sound": "grenade",
		"tracer_speed": 55.0,
	},
}


## Stats da arma; dicionario vazio para faca/pistola padrao.
## Uso: var stats := WeaponStats.stats_for(kind)
static func stats_for(kind: int) -> Dictionary:
	return STATS_BY_KIND.get(kind, {})


## So armas de crate degradam; faca e pistola padrao sao permanentes.
## Uso: if WeaponStats.is_crate_weapon(kind): ...
static func is_crate_weapon(kind: int) -> bool:
	return STATS_BY_KIND.has(kind)


## Armas de crate em ordem de tipo (fonte unica para crate, drop e modelos).
## Uso: for kind in WeaponStats.crate_kinds(): ...
static func crate_kinds() -> Array[int]:
	var kinds: Array[int] = []
	for kind in STATS_BY_KIND:
		kinds.append(int(kind))
	kinds.sort()
	return kinds


## Cor do corpo da arma (modelo na mao, pickup no chao e crate).
## Uso: var cor := WeaponStats.color_for(WeaponStats.Kind.UZI)
static func color_for(kind: int) -> Color:
	return stats_for(kind).get("color", Color(0.2, 0.2, 0.2))


## Tamanho do tracer (bala grossa da magnum, feixe longo do laser, foguete da bazuca).
## Uso: var escala := WeaponStats.tracer_scale_for(WeaponStats.Kind.SNIPER)
static func tracer_scale_for(kind: int) -> Vector3:
	return stats_for(kind).get("tracer_scale", Vector3.ONE)


## Velocidade do tracer visual. Armas de crate dao dano na hora (hitscan): o
## tracer lento (16 m/s) chegava depois do zumbi ja ferido/morto e parecia
## dessincronizado. Faca/pistola (projetil real) seguem com a velocidade da bala.
## Uso: bullet.speed = WeaponStats.tracer_speed_for(WeaponStats.Kind.LASER_RIFLE)
static func tracer_speed_for(kind: int) -> float:
	return float(stats_for(kind).get("tracer_speed", 0.0))


## Perfil de som do tiro (WeaponSoundSynth); faca/pistola usam "pistol".
## Uso: var perfil := WeaponStats.sound_for(WeaponStats.Kind.SNIPER)
static func sound_for(kind: int) -> String:
	return String(stats_for(kind).get("sound", "pistol"))


## Recuo da animacao: x = coice para tras (m), y = cano subindo (rad).
## Uso: var recuo := WeaponStats.recoil_for(WeaponStats.Kind.MAGNUM)
static func recoil_for(kind: int) -> Vector2:
	var stats := stats_for(kind)
	return Vector2(float(stats.get("recoil", 0.0)), float(stats.get("recoil_lift", 0.0)))


## Cor do tracer: cada arma tem a sua; faca/pistola usam o amarelo padrao.
## Uso: var cor := WeaponStats.tracer_color_for(WeaponStats.Kind.PLASMA_SMG)
static func tracer_color_for(kind: int) -> Color:
	return stats_for(kind).get("tracer_color", DEFAULT_TRACER_COLOR)
